-- ==================================================
-- CONFIG
-- ==================================================
Pos1 = { x = 2, y = 0, z = 0 }
Pos2 = { x = 0, y = 0, z = 0 }
Pos3 = { x = -2.0, y = 0, z = 0 }
PosDestination = { x = 0, y = 2, z = 5 }
-- ==================================================
-- VARIABLES
-- ==================================================

Card1 = nil
Card2 = nil
Card3 = nil

-- ==================================================
-- ON LOAD
-- ==================================================
function onLoad()
    self.createButton({
        label = "DUPLICATE",
        click_function = "buttonPressed",
        function_owner = self,
        position = { 0, 0.3, -2 },
        rotation = { 0, 0, 0 },
        width = 1800,
        height = 600,
        font_size = 300
    })
end
-- =========================
-- BUTTON
-- =========================
function buttonPressed(obj, player_color, alt_click)
    
    -- Cards are sticky. Lock to prevent annoying.
    self.setLock(true)

    detectThreeCards(player_color)

    if not Card1 then
        printToAll("No card to stamp detected. Please place a card at the left position.")
        return
    end
    if not Card2 then
        printToAll("No card to stamp detected. Please place a card at the central position.")
        return
    end
    
    local spawnInfo = getCardData(Card1)
    
    -- Depending on the card, do different things

    if Card1.getName() == "Grizzled" then
        local fieldsInfo = getGrizzledTraits(Card2)
        local nemesisField = getGrizzledNemesis(Card2)
        if Card3 and Card3.getName then
            invName = Card3.getName()
        else 
            invName = nil
        end
        spawnGrizzledFromData(spawnInfo, fieldsInfo, nemesisField, invName, { position = PosDestination })
    elseif Card1.getName() == "Runic Axe" then
        error("not impl")
    end


    
end

-- =========================
-- DETECTION
-- =========================

function detectThreeCards(player_color)
    -- ping positions for debug
    Player[player_color].pingTable(self.positionToWorld(Pos1))
    Player[player_color].pingTable(self.positionToWorld(Pos2))
    Player[player_color].pingTable(self.positionToWorld(Pos3))
    -- detect objects
    Card1 = detectCard(Pos1)
    Card2 = detectCard(Pos2)
    Card3 = detectCard(Pos3)
    
    if Card1 then
        printToAll("Card to stamp detected: " .. Card1.getName())
    else
        printToAll("No card found at left position.")
    end
    if Card2 then
        printToAll("Upgrade Sheet detected: " .. Card2.getName())
    else
        printToAll("No card found at central position.")
    end
    if Card3 then
        print("Investigator Card detected: " .. Card3.getName())
    else
        printToAll("No card found at right position.")
    end
end

function detectCard(position)

    local hits = Physics.cast({
        origin = self.positionToWorld(position) + Vector(0, 1, 0),
        direction = { 0, -1, 0 },
        type = 1,         -- RAY
        max_distance = 5, -- how far down to search
        debug = false
    })
    for _, hit in ipairs(hits) do
        local obj = hit.hit_object
        if obj.getName() == "Card duplicator" then
            return nil
        elseif obj.tag == "Card" then
            return obj
        end
    end

    return nil
end

--- =========================
--- GET CARDS DATA
--- =========================

-- This card gets a lot of info, to be able to spawn a card
---@param card tts__Object: a card
---@return table: a table that can be passed to spawnObject
function getCardData(card)

    if not card then
        error("No card provided", 2)
    end

    if not card.getName or not card.getDescription or not card.getGUID then
        error("Invalid card object", 2)
    end

    if card.tag ~= "Card" then
        error("Object is not a card", 2)
    end

    local data = {}
    data.name = card.getName()
    data.description = card.getDescription()
    data.guid = card.getGUID()
    data.position = card.getPosition()
    data.rotation = card.getRotation()
    data.scale = card.getScale()
    data.gmNotes = card.getGMNotes()
    data.tags = card.getTags()
    data.custom = card.getCustomObject()
    data.luaScript = card.getLuaScript()
    local success, state = pcall(function()
        return card.getLuaScriptState()
    end)
    data.luaScriptState = success and state or ""
    return data
end

-- This takes the Upgrade Sheet of Grizzled, and grabs the traits
function getGrizzledTraits(card)
    if not card or card.script_state == "" then
        return {}
    end
    
    local data = JSON.decode(card.script_state)
    local allTraits = {}
    if data and data.selections then
        for _, entry in ipairs(data.selections) do
            if entry.text and entry.text ~= "" then
                for trait in string.gmatch(entry.text, "([^,]+)") do
                    trait = trait:match("^%s*(.-)%s*$")
                    table.insert(allTraits, trait)
                end
            end
        end
    end
    return allTraits
end

---@return boolean
function getGrizzledNemesis(card)
    log("enter ggt")
    local hasNemesis = false
    if not card or card.script_state == "" then
        return false
    end
    pcall(function() hasNemesis =  JSON.decode(card.script_state).selections[4]["xp"] == 3
    end)
    
    if hasNemesis then
        log("This is indeed nemesis")
    end

    return hasNemesis
end

function getRunicAxeUpgrades(card)
    if not card or card.script_state == "" then
        return {}
    end
    log(JSON.decode(card.script_state))
end

-- =========================
-- SPAWN CARDS
-- =========================

---@param data table 
---@param invName string|nil
---@param upgradeFields table
---@param nemesisField boolean
---@param params table
function spawnGrizzledFromData(data, upgradeFields, nemesisField, invName, params)
    if not data or not data.custom then
        error("Invalid card data", 2)
    elseif not upgradeFields or type(upgradeFields) ~= "table" then
        error("Invalid fields data, expected a table", 2)
    elseif type(invName) ~= "string" and invName ~= nil then
        error("Invalid name, expected a string or nil", 2)
    elseif type(nemesisField) ~= "boolean" and nemesisField ~= nil then
        error("Invalid nemesisField, expected bool or nil", 2)
    end

    local destination = self.positionToWorld(params.position)
    
    if invName == nil then
        printToAll('not implemented yet, its awful')
        URL =
        "https://arkhamdb.com/bundles/cards/09101.png"
    elseif invName == 'George Barnaby' then
        URL =
        "https://steamusercontent-a.akamaihd.net/ugc/15253478470813349064/9A6F7DEA828EA4519C35CDFD80D73C35CA63ABD7/"
    elseif invName == 'Hank Samson' then
        URL =
        "https://steamusercontent-a.akamaihd.net/ugc/17554546592286588821/04A62CFDE0B5C40FE0A04433D0707A9F828889ED/"
    elseif invName == 'Hank Samson (Assistant)' then
        URL =
        "https://steamusercontent-a.akamaihd.net/ugc/17554546592286588821/04A62CFDE0B5C40FE0A04433D0707A9F828889ED/"
    elseif invName == 'Hank Samson (Warden)' then
        URL =
        "https://steamusercontent-a.akamaihd.net/ugc/17554546592286588821/04A62CFDE0B5C40FE0A04433D0707A9F828889ED/"
    elseif invName == 'Isabelle Barnes' then
        URL =
        "https://steamusercontent-a.akamaihd.net/ugc/10359671553347854014/56EAB6453121511654D21C83241881E438A81EFC/"
    elseif invName == 'Minh Thi Phan' then
        URL =
        "https://steamusercontent-a.akamaihd.net/ugc/13841382499082651366/6B4E9FEAFE291A5DC3C6734C11CBD64330FFCBCF/"
    else
        -- Any investigator that is not implemented
        URL =
        "https://arkhamdb.com/bundles/cards/09101.png"
    end
    
    local spawnParams = {
        type = "CardCustom",
        position = destination,
        rotation = data.rotation,
        -- more data from params
    }

    local newCard = spawnObject(spawnParams)
    
    -- Apply appearance
    newCard.setCustomObject({
        face = URL,
        back = data.custom.back,
        number = 1,
        back_is_hidden = true
    })
    -- Apply metadata
    newCard.setName(data.name)
    newCard.setDescription(data.description)
    newCard.setGMNotes(data.gmNotes)
    
    -- Apply tags
    for _, tag in ipairs(data.tags or {}) do
        newCard.addTag(tag)
    end
    
    
    -- █▀▄▀█ █▀▀ ▀█▀ ▄▀█ ▄▄ █▀ █▀▀ █▀█ █ █▀█ ▀█▀
    -- █░▀░█ ██▄ ░█░ █▀█ ░░ ▄█ █▄▄ █▀▄ █ █▀▀ ░█░
    
    
    assert(upgradeFields, "This should exist. april 26")
    
    for _, element in ipairs(upgradeFields) do
        printToAll('-    Grizzled has the trait: ' .. element)
    end

    setScriptWise(newCard, upgradeFields, nemesisField)
 
    return newCard
end

function setScriptWise(card, fieldsOuter, nemesisOuter)
    -- 1. Outer Constants
    local posX = 0
    local posY = 71
    local posYnemesis = 71
    local posZ = -40
    local width = 180
    local height = 24
    local scale = "1 1 1"
    local rotation = "0 0 180"
    local fSize = 8
    local nemesisLua = nemesisOuter
    
    local workingFields = {}
    workingFields = fieldsOuter

    -- Format table for the generated LUA script
    -- This turns {"A", "B"} into {"A", "B"} as a literal string
    local fieldsLua = '{"' .. table.concat(workingFields, '", "') .. '"}'

    if #workingFields == 2 then
        fSize = 15
        posYnemesis = posY
    elseif #workingFields == 3 then
        fSize = 15
        posYnemesis = posY + 20
    elseif #workingFields == 4 then
        fSize = 15
        posYnemesis = posY
    end

    if #workingFields == 3 then
        additonalXml = [[-- Add nemesis box
    xml = xml .. '<Panel width="]] .. width + 20 ..
            [[" height="]] .. height .. [["' position = "]] .. posX .. [[  ]] .. posY .. [[  ]] .. posZ .. [["  bestFitMaxSize="'..globalFontSize..'"/>'
        xml = xml .. '  <Text text="NeMeSiS" fontSize="7" color="#0055ff" rectAlignment="MiddleCenter" />'
        xml = xml .. '</Panel>'
        ]]
        printToAll("This card has 3 traits, so the nemesis tag will be moved down to avoid overlap.")
    end
    

    local cardScript = [[
-- Generated Script

local fields = ]] .. fieldsLua .. [[

local globalFontSize = ]] .. fSize .. [[


function onLoad()
    -- Wait a frame to ensure UI is ready
    Wait.frames(function() self.UI.setXml(generateCardXml()) end, 1)
end

function getCell(txt)
    local xml = '<Panel>'
    xml = xml .. '<Text text="'..txt..'" fontSize="'..globalFontSize..'"  '
    xml = xml .. 'color="#000000" rectAlignment="MiddleCenter" bestFit="true" bestFitMinSize="6"'
    xml = xml .. 'position = "]] .. posX .. [[  ]] .. posY .. [[  ]] .. posZ .. [["  bestFitMaxSize="'..globalFontSize..'"/>'
    xml = xml .. '</Panel>'
    return xml
end

function generateCardXml()
    local num = #fields
    local xml = '<Panel id="DebugBox" width="]] .. width .. [[" height="]] .. height .. [[" color="#00000000">'

    if num == 2 then
        xml = xml .. '<HorizontalLayout spacing="1">'
        xml = xml .. getCell(fields[1])
        xml = xml .. getCell(fields[2])
        xml = xml .. '</HorizontalLayout>'

    elseif num == 3 then
        xml = xml .. '<HorizontalLayout spacing="1">'
        xml = xml .. getCell(fields[1])
        xml = xml .. getCell(fields[2])
        xml = xml .. getCell(fields[3])
        xml = xml .. '</HorizontalLayout>'

    elseif num == 4 then
        xml = xml .. '<VerticalLayout spacing="0">'
            xml = xml .. '<HorizontalLayout height="12" spacing="1">'
                xml = xml .. getCell(fields[1])
                xml = xml .. getCell(fields[2])
            xml = xml .. '</HorizontalLayout>'
            xml = xml .. '<HorizontalLayout height="12" spacing="1">'
                xml = xml .. getCell(fields[3])
                xml = xml .. getCell(fields[4])
            xml = xml .. '</HorizontalLayout>'
        xml = xml .. '</VerticalLayout>'
    else
        error("Some message", 2)
    end

    ]] .. additonalXml .. [[

    xml = xml .. '</Panel>'
    return xml
end
]]

    card.setLuaScript(cardScript)
    card.reload()
end
