local PlayermatApi = require("playermat/PlayermatApi")

DEBUG              = false

RETRIEVABLE_CARDS  = {
  "04312", "04033", "11092",
  "04272", "10118", "11085",
  "11090", "06245", "09103"
}


-- ====================
-- BUILT-IN
-- ====================


function onLoad(saved_data)
  discard               = nil
  playermatColor        = nil
  investigatorId        = nil
  foundRetrievableNames = {}
  isScavenging          = false
  isAmuletActive        = false
  isIsabelle            = false
  isAgatha              = false
  isWendy               = false
  isWilliam             = false

  self.createButton({
    click_function = "detectMat", 
    function_owner = self,
    position = { 0, 1, 0 },
    rotation = { 0, 0, 0 },
    height = 1000,
    width = 1000,
    color = { 1, 1, 1, 1 },
    tooltip = tooltip
  })

end

function onSave()
  local data_to_save = {
    discard               = discard,
    foundRetrievableNames = foundRetrievableNames,
    investigatorId        = investigatorId,
    isAgatha              = isAgatha,
    isAmuletActive        = isAmuletActive,
    isIsabelle            = isIsabelle,
    isScavenging          = isScavenging,
    isWendy               = isWendy,
    isWilliam             = isWilliam,
    playermatColor        = playermatColor
  }
  return JSON.encode(data_to_save)
end

function onHover()
  readDiscardPile(DEBUG)
  generateContextMenu()
end

-- ====================
-- START
-- ====================

function detectMat()
  playermatColor = PlayermatApi.getMatColorByPosition(self.getPosition())
  if not playermatColor then
    return
  else
    printToAll('The helper found the ' .. playermatColor .. ' mat.')
  end
  detectInvestigatorLoudly()
  addPermanentEntries()
  self.removeButton(0)
end

-- ====================
-- Context Menu
-- ====================

-- This function generates the context menu based on the current state of the discard pile and the toggles
function generateContextMenu()
  self.clearContextMenu()
  addPermanentEntries()
  for _, name in pairs(foundRetrievableNames) do
    self.addContextMenuItem(name, function() pullCardFromDiscard(name) end)
  end
end

-- This entries always lead the context menu
function addPermanentEntries()
  self.addContextMenuItem("Toggle Scavenging", function() toggleScavenging() end)
  if isWendy then
    self.addContextMenuItem("Toggle Wendy's Amulet", function() toggleAmulet() end)
  end
end

function toggleScavenging()
  isScavenging = not isScavenging
  printToAll("Retrieving Items is now " .. (isScavenging and "active" or "inactive"), { 1, 1, 1 })
end

function toggleAmulet()
  isAmuletActive = not isAmuletActive
  printToAll("Retrieving Events is now " .. (isScavenging and "active" or "inactive"), { 1, 1, 1 })
end

-- ====================
-- MAJOR FUNCTIONS
-- ====================

--- Seaches discard pile, reads and populates the foundRetrievable variable
--- @debug boolean, if true, will print debug messages. Default false.
--- @return nil
function readDiscardPile(debug)
  local debug = debug or false

  if not playermatColor and debug then
    log("readDiscardPile has no player mat. This is unexpected.")
    return
  end

  local deckAreaObjects = PlayermatApi.getDeckAreaObjects(playermatColor)

  if not deckAreaObjects then
    if debug then log("read discard pile can't get deck area objects") end
    return
  end

  discard = deckAreaObjects.discard or nil
  if not discard then
    foundRetrievableNames = {}
    return
  end

  foundRetrievableNames = {}

  if discard.type == 'Card' and debug then
    local card = discard
    ifRetrievableAdd(card)
  elseif discard.type == 'Deck' then
    for _, card in ipairs(deckAreaObjects.discard.getObjects()) do
      ifRetrievableAdd(card)
    end
  end
end

---@param cardName string
---@return nil|tts__Object
function pullCardFromDiscard(cardName)
  if type(cardName) ~= "string" then
    error("Implementation error. Expected string.", 2)
  end

  local matColor = PlayermatApi.getMatColorByPosition(self.getPosition())
  local deckAreaObjects = PlayermatApi.getDeckAreaObjects(matColor)

  if not deckAreaObjects.discard then
    return
  end

  if deckAreaObjects.discard.type == 'Card' and debug then
    log("Yet to implement", 2)
  elseif deckAreaObjects.discard.type == 'Deck' then
    return takeOutByName(deckAreaObjects.discard, cardName, {
      position = self.getPosition() + Vector(0, 1, 0), smooth = true })
  end
end

-- ====================
-- Boolean helpers
-- ====================

--- Absolute ifRetrievableAdd function, checks if the card is retrievable by any means and add it to the list if so
---@return nil
function ifRetrievableAdd(card)
  if type(card) ~= "table" then
    error("Yet to implement", 2)
  end

  if not card.gm_notes then
    error("Fail immediately in the developing. All SCED cards have gmnotes.", 2)
  end

  if isPlayableCard(card.gm_notes) then
    table.insert(foundRetrievableNames, card.name)
  elseif isScavenging and isScavengingAble(card.gm_notes) then
    table.insert(foundRetrievableNames, card.name)
  elseif isAmuletActive and isEvent(card.gm_notes) then
    table.insert(foundRetrievableNames, card.name)
  elseif isIsabelle and isSkill(card.gm_notes) then
    table.insert(foundRetrievableNames, card.name)
  elseif isWilliam and isAsset(card.gm_notes) then
    table.insert(foundRetrievableNames, card.name)
  elseif isAgatha and isAgathaAble(card.gm_notes) then
    table.insert(foundRetrievableNames, card.name)
  end
end

--- Checks if this is a playable Card, simply by its effect
---@return boolean
function isPlayableCard(gmnotes)
  local metadata = JSON.decode(gmnotes) or {}
  if isInList(RETRIEVABLE_CARDS, metadata.id) then
    return true
  end
  return false
end

--- Checks if this is an Item Card
---@return boolean
function isScavengingAble(gmnotes)
  local metadata = JSON.decode(gmnotes) or {}
  traits = metadata.traits or ""
  if string.find(traits, "Item") then
    return true
  end
  return false
end

-- Checks if this is an Event
function isEvent(gmnotes)
  local metadata = JSON.decode(gmnotes) or {}
  if metadata.type == "Event" then
    return true
  end
  return false
end

--- Checks if this is a Skill
--- @return boolean
function isSkill(gmnotes)
  local metadata = JSON.decode(gmnotes) or {}
  if metadata.type == "Skill" then
    return true
  end
  return false
end

--- Checks if this is an Event, and has the insight or spell trait
---@return boolean
function isAgathaAble(gmnotes)
  local metadata = JSON.decode(gmnotes) or {}

  if metadata.type == "Event" and metadata.traits then
    if string.find(metadata.traits, "Spell") or string.find(metadata.traits, "Insight") then
      return true
    end
  end

  return false
end

--- Checks if this is an Asset
--- @return boolean
function isAsset(gmnotes)
  local metadata = JSON.decode(gmnotes) or {}
  if metadata.type == "Asset" then
    return true
  end
  return false
end

-- get investigatorId
---@return string|nil
function getInvestigatorId()
  if not playermatColor then
    return nil
  end
  local data = PlayermatApi.getActiveInvestigatorData(playermatColor)
  return data.id or nil
end

-- ====================
-- ADDITIONAL
-- ====================

--- Sets the variables isX
function detectInvestigatorLoudly()
  investigatorId = getInvestigatorId()

  if investigatorId == "12013" then
    isIsabelle = true
    printToAll("Discard Retriever: Isabelle Barnes detected.", { 1, 1, 1 })
  elseif investigatorId == "11007" or investigatorId == "11008" then
    isAgatha = true
    printToAll("Discard Retriever: Agatha Crane detected.", { 1, 1, 1 })
    printToAll("Warning! This helper for Agatha helps you retrieve some events.", { 1, 0, 0 })
    printToAll("Agatha's retrievable events are trickly, and some events can't be played with her ability.", { 1, 0, 0 })
  elseif string.find(investigatorId, "01005") then
    isWendy = true
    printToAll("Discard Retriever: Wendy Adams detected.", { 1, 1, 1 })
  elseif investigatorId == "03005" then
    isWilliam = true
    printToAll("Discard Retriever: Will Yorick detected.", { 1, 1, 1 })
  else
    printToAll("Discard Retriever: " .. investigatorId)
    local investigatorName = PlayermatApi.getInvestigatorName(matColor)
    printToAll("Discard Retriever: " .. investigatorName .. " detected.")
  end
end

--- ===================================================
--- GENERIC FUNCTIONS FOR TABLETOP SIMULATOR
--- ===================================================

--- Takes out a card by name from a deck, and put it in front of the helper
---@param deck tts__Object
---@param cardName string
---@returns tts__Object|nil
function takeOutByName(deck, cardName, params)
  -- Defensive checks

  if not deck or deck.tag ~= "Deck" then
    error("Argument error. deck", 2)
  end

  if type(cardName) ~= "string" or cardName == "" then
    error("Argument error. cardName", 2)
  end

  if not params or type(params) ~= "table" then
    error("Argument error. params", 2)
  end

  -- Search for the card in the deck
  local cards = deck.getObjects()
  for _, card in ipairs(cards) do
    if card.name == cardName then
      if card.name == cardName then
        deck.takeObject({ guid = card.guid, position = self.getPosition() + Vector(0, 1, 0.5), smooth = false })
        break
      end
    end
  end

  log("takeoutbyname: Card '" .. cardName .. "' not found in deck")
  return nil
end

--- Checks if a value is in a list
---@param list table of card id
---@param value string card id to search for
---@return boolean
function isInList(list, value)
  for _, item in ipairs(list) do
    if item == value then
      return true
    end
  end
  return false
end
