local PlayermatApi  = require("playermat/PlayermatApi")

retrievableCardsIds = {
  "04312", "04033", "11092",
  "04272", "10118", "11085",
  "11090", "06245", "09103"
}


--- @type string[]
local foundRetrievableNames = {}
local isScavenging = false
local isAmuletActive = false
local isIsabelle = false


function onLoad()
  -- Check if its Isabelle
  if isInvestigatorIsabelle() then
    isIsabelle = true
    printToAll("Discard Retriever: Isabelle Barnes detected.", { 1, 1, 1 })
  end

  addPermanentEntries()
end

function onHover()
  readDiscardPile()
  generateContextMenu()
end

-- Context Menu

-- This function generates the context menu based on the current state of the discard pile and the toggles
function generateContextMenu()
  self.clearContextMenu()

  -- Permanent toggles
  addPermanentEntries()

  -- Cards stored as retrievable Cards, generate entries
  for _, name in pairs(foundRetrievableNames) do
    self.addContextMenuItem(name, function() pullCardFromDiscard(name) end)
  end
end

-- This entries always lead the context menu
function addPermanentEntries()
  self.addContextMenuItem("Toggle Scavenging", function() toggleScavenging() end)
  self.addContextMenuItem("Toggle Wendy's Amulet", function() toggleAmulet() end)
end

function toggleScavenging()
  isScavenging = not isScavenging
  printToAll("Retrieving Items is now " .. (isScavenging and "active" or "inactive"), { 1, 1, 1 })
end

function toggleAmulet()
  isAmuletActive = not isAmuletActive
  printToAll("Retrieving Events is now " .. (isScavenging and "active" or "inactive"), { 1, 1, 1 })
end

-- seaches discard pile, reads and populates the foundRetrievable variable
function readDiscardPile()
  local matColor = PlayermatApi.getMatColorByPosition(self.getPosition())
  local deckAreaObjects = PlayermatApi.getDeckAreaObjects(matColor)
  foundRetrievableNames = {}

  if not deckAreaObjects.discard then return end

  if deckAreaObjects.discard.type == 'Card' then
    addRetrievableCard(deckAreaObjects.discard)
  elseif deckAreaObjects.discard.type == 'Deck' then
    for _, card in ipairs(deckAreaObjects.discard.getObjects()) do
      addRetrievableCard(card)
    end
  end
end

---@param cardName string
---@return tts__Object|nil
function pullCardFromDiscard(cardName)
  if type(cardName) ~= "string" then
    error("Implementation error. Expected string.", 2)
  end

  local matColor = PlayermatApi.getMatColorByPosition(self.getPosition())
  local deckAreaObjects = PlayermatApi.getDeckAreaObjects(matColor)
  local obj = nil

  if not deckAreaObjects.discard then
    return nil
  end

  if deckAreaObjects.discard.type == 'Card' then
    obj = deckAreaObjects.discard.setPositionSmooth(self.getPosition() + Vector(0, 1, 0), false, true)
  elseif deckAreaObjects.discard.type == 'Deck' then
    obj = takeOutByName(deckAreaObjects.discard, cardName, {
      position = self.getPosition() + Vector(0, 1, 0), smooth = true })
  end
  return obj
end

-- Boolean helpers

-- Absolute function, checks if the card is retrievable by any means
-- adds it to the foundRetrievableNames
---@param card tts__Object or table -- card can be a table (inside a deck) or a userdata (a single card on the discard pile)
---@return nil
function addRetrievableCard(card)
  if type(card) ~= "table" and type(card) ~= "userdata" then
    log("Implementation error, should not be called", 2)
  end

  local gmNotes = {}
  local name = nil
  if type(card) == "table" then
    gmNotes = card.gm_notes
    name = card.name
  elseif type(card) == "userdata" then
    gmNotes = card.getGMNotes()
    name = card.getName()
  end

  if not name or not gmNotes then
    log("Implementation error, card has no name or gmnotes")
    return
  end


  if isPlayableCard(gmNotes) then
    table.insert(foundRetrievableNames, name)
  elseif isScavenging and isScavengingAble(gmNotes) then
    table.insert(foundRetrievableNames, name)
  elseif isAmuletActive and isEvent(gmNotes) then
    table.insert(foundRetrievableNames, name)
  elseif isIsabelle and isSkill(gmNotes) then
    table.insert(foundRetrievableNames, name)
  end
end

-- Checks if this is a playable Card, simply by its effect
---@return boolean
function isPlayableCard(gmnotes)
  local metadata = JSON.decode(gmnotes) or {}
  if isInList(retrievableCardsIds, metadata.id) then
    return true
  end
  return false
end


--- Checks if this is an Item Card
---@return boolean
function isScavengingAble(gmnotes)
  local metadata = JSON.decode(gmnotes) or {}
  traits = metadata.traits or ""
  if string.find(traits, "Item") then
    return true
  end
  return false
end

---@return boolean
-- Checks if this is an Event
function isEvent(gmnotes)
  local metadata = JSON.decode(gmnotes) or {}
  if metadata.type == "Event" then
    return true
  end
  return false
end

---@return boolean
-- Checks if this is an Skill
function isSkill(gmnotes)
  local metadata = JSON.decode(gmnotes) or {}
  if metadata.type == "Skill" then
    return true
  end
  return false
end

---@return boolean
function isInvestigatorIsabelle()
  local matColor = PlayermatApi.getMatColorByPosition(self.getPosition())
  local investigator = PlayermatApi.getActiveInvestigatorData(matColor)
  if investigator and investigator.id == "12013" then
    return true
  end
  return false
end

------ GENERIC FUNCTIONS FOR TABLETOP SIMULATOR

---@param deck tts__Object
---@param cardName string
---@return tts__Object|nil
function takeOutByName(deck, cardName, params)
  -- Defensive checks

  if not deck or deck.tag ~= "Deck" then
    error("Argument error. deck", 2)
  end

  if type(cardName) ~= "string" or cardName == "" then
    error("Argument error. cardName", 2)
  end

  if not params or type(params) ~= "table" then
    error("Argument error. params", 2)
  end

  -- Search for the card in the deck
  local cards = deck.getObjects()
  for _, card in ipairs(cards) do
    if card.name == cardName then
      if card.name == cardName then
        deck.takeObject({ guid = card.guid, position = self.getPosition() + Vector(0, 1, 0.5), smooth = false })
        break
      end
    end
  end

  log("takeoutbyname: Card '" .. cardName .. "' not found in deck")
  return nil
end

--@param list table of card id
--@param value id to search for
---@return boolean
function isInList(list, value)
  for _, item in ipairs(list) do
    if item == value then
      return true
    end
  end
  return false
end
